# AWSTemplateFormatVersion: '2010-09-09'
# Transform: AWS::Serverless-2016-10-31
# Resources:
#   SongRecommenderFunction:
#     Type: AWS::Serverless::Function
#     Properties:
#       PackageType: Image
#       ImageUri: bollywoodsongrecommendationsystem:local
#       Timeout: 30
#       Events:
#         Api:
#           Type: Api
#           Properties:
#             Path: /
#             Method: ANY
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  SongRecommenderFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: bollywoodsongrecommendationsystem:latest  # Ensure you use the correct tag for your ECR image
      Timeout: 900
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: ANY
Outputs:
  ApiUrl:
    Description: "URL for endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
